### ISSUE TITLE
Maintainership status

### ISSUE THREAD

**Issue by vi** [Lucretiel/gridly-rs#5]
Are you planning to continue maintaining of `gridly` and `gridly-grids`? There is at least one long-unattended pull request.

If not, it is better to at least mark the project as abandoned explicitly in the README, or (a stretch goal) find other maintainers.

**Comment by Lucretiel** [comment]
This project is not abandoned by any means, I still use it myself all the time. My ability to work on it fluctuates based on a lot of things, but it is still something I work on.

Looking at the PR– it basically looks good, but some things about it are a bit out of date now that min const generics are stabilized. I'll add a review.
